### ISSUE TITLE
Cambiar expresion regular para aceptar espacios en blanco al principio

### ISSUE THREAD

**Issue by alu0100782851** [ULL-ESIT-GRADOII-DSI/introduccion-javi_dsi1516#11]

**Comment by alu0100505009** [comment]
Completado, la expresion regular queda de la siguiente manera:
var regexp = /^(\s)_([-+]?\d+(?:.\d_)?([e][-+]?\d+)?)\s_((f(a(h(r(e(n(h(e(i(t)?)?)?)?)?)?)?)?)?)|(c(e(l(s(i(u(s)?)?)?)?)?)?))\s_$/i;
