### ISSUE TITLE
Modificar el README.md para añadir los links, similar a la práctica anterior. (Copy/Paste del mensaje)

### ISSUE THREAD

**Issue by alu0100505009** [ULL-ESIT-GRADOII-DSI/introduccion-javi_dsi1516#7]
# **-Practica 2 de Desarrollo de Sistemas Informáticos-**

[Link al campus de la asignatura](https://campusvirtual.ull.es/1516/course/view.php?id=144)

Componentes:

> -Javier Pestano Ron

[Página personal](http://alu0100505009.github.io/)

[Repositorio Personal](https://github.com/alu0100505009/introduccion-javi_dsi1516)

[Página de la práctica](http://ull-esit-gradoii-dsi.github.io/introduccion-javi_dsi1516)

> -Moisés Yanes Carballo

[Página personal](http://alu0100782851.github.io/)

[Repositorio Personal](https://github.com/alu0100782851/introduccion-javi_dsi1516)

[Página de la práctica](http://ull-esit-gradoii-dsi.github.io/tintroduccion-javi_dsi1516)

> -Alexander Cole Mora

[Página personal](http://alu0100767421.github.io/)

[Repositorio Personal](https://github.com/alu0100767421/introduccion-javi_dsi1516)

[Página de la práctica](http://ull-esit-gradoii-dsi.github.io/introduccion-javi_dsi1516)

**Comment by crguezl** [comment]
:+1:

**Comment by alu0100782851** [comment]
Readme modificado, con enlaces añadidos!
