### ISSUE TITLE
Cambiar la rama por defecto a gh-pages

### ISSUE THREAD

**Issue by alu0100767421** [ULL-ESIT-GRADOII-DSI/introduccion-javi_dsi1516#8]

**Comment by alu0100505009** [comment]
Mi repositorio personal ya contiene el gh-pages como rama principal.

**Comment by alu0100767421** [comment]
Mi repositorio personal también tiene el gh-pages como rama principal

**Comment by alu0100782851** [comment]
Mi repositorio personal ya tiene también la rama gh-pages como rama principal y cierro el issue
